# Generated by Django 5.0.3 on 2024-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='products',
        ),
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(to='shop.product', verbose_name='Продукты'),
        ),
    ]
