# Generated by Django 5.0.3 on 2024-03-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_vendor_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contacts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.contact', verbose_name='Контакты'),
        ),
    ]
