# Generated by Django 5.0.3 on 2024-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_vendor_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='hierarchy_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Уровень иерархии'),
        ),
    ]
