# Generated by Django 5.0.3 on 2024-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_vendor_hierarchy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='hierarchy_level',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Уровень иерархии'),
        ),
    ]
